b8:
    database:
        servers:
            read: mysql
            write: mysql
        name: phpci
        username: phpci
        password: phpci
        port: 3307
phpci:
    url: 'http://88.146.49.119:8090'