phpci:
    build: .
    ports:
      - "8090:80"
    expose:
      - "8090"
    links:
        - mysql:database
    volumes:
        - .:/var/app

mysql:
    image: mysql/mysql-server:5.7
    ports:
        - 3307:3306
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw -d
        - MYSQL_DATABASE=phpci
        - MYSQL_USER=phpci
        - MYSQL_PASSWORD=phpci


