phpci:
    build: .
    ports:
      - "8090:80"
      - "9002:9002"
    expose:
      - "8090"
      - "9002"

    links:
        - mysql:database
        - postgres:database
        - redis:redis
        - pdfgen:pdfgen
        - rabbitMQ:rabbitMQ
        - mysql:mysql
        - elasticsearch:elasticsearch
    volumes:
        - .:/var/app

mysql:
    image: mysql/mysql-server:5.7
    ports:
        - 3307:3306
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw -d
        - MYSQL_DATABASE=phpci
        - MYSQL_USER=phpci
        - MYSQL_PASSWORD=phpci


elasticsearch:
  image: elasticsearch:latest
#  build: ./docker/elasticSearch
  ports:
    - 9301:9300
    - 9201:9200

redis:
  build: ./docker/redis/
  ports:
    - 6380:6379
  volumes:
    - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  restart: always

postgres:
  image: postgres:9.4
  ports:
    - 5433:5432
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pass
    - DEBUG=false

pdfgen:
  image: nousefreak/pdfgen
  ports:
    - 7421:80
  expose:
    - 7421

rabbitMQ:
  image: rabbitmq:3-management
  ports:
    - "5673:5672"
    - "15673:15672"
  volumes:
    - /opt/Data/Rabbitmq:/var/lib/rabbitmq